/*
 * Adds durable, tenant-safe student annual progression history.
 *
 * Preview remains stateless. These tables are written only when a
 * confirmation request creates a durable progression operation.
 */


/*
 * Enables tenant-safe composite foreign keys from progression items
 * to student enrollments.
 */
ALTER TABLE student_enrollments
    ADD CONSTRAINT uk_student_enrollment_id_organization
        UNIQUE (id, organization_id);


/*
 * One row represents one bounded progression confirmation operation.
 */
CREATE TABLE student_progression_operations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    source_academic_year_id BIGINT NOT NULL,
    target_academic_year_id BIGINT NOT NULL,
    batch_label VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(71) NOT NULL,
    preview_fingerprint VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    total_items INTEGER NOT NULL,
    failure_code VARCHAR(80),
    failure_message VARCHAR(500),
    result_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_progression_operation_id_organization
        UNIQUE (id, organization_id),

    CONSTRAINT uk_student_progression_operation_tenant_idempotency
        UNIQUE (organization_id, idempotency_key),

    CONSTRAINT chk_student_progression_operation_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_student_progression_operation_source_year_positive
        CHECK (source_academic_year_id > 0),

    CONSTRAINT chk_student_progression_operation_target_year_positive
        CHECK (target_academic_year_id > 0),

    CONSTRAINT chk_student_progression_operation_user_positive
        CHECK (requested_by_user_id > 0),

    CONSTRAINT chk_student_progression_operation_distinct_years
        CHECK (
            source_academic_year_id
                <> target_academic_year_id
            ),

    CONSTRAINT chk_student_progression_operation_batch_label
        CHECK (BTRIM(batch_label) <> ''),

    CONSTRAINT chk_student_progression_operation_total_items
        CHECK (total_items BETWEEN 1 AND 2000),

    CONSTRAINT chk_student_progression_operation_hash_format
        CHECK (
            request_hash ~ '^sha256:[0-9a-f]{64}$'
                AND preview_fingerprint
                ~ '^sha256:[0-9a-f]{64}$'
            ),

    CONSTRAINT chk_student_progression_operation_status
        CHECK (
            status IN (
                       'PENDING',
                       'RUNNING',
                       'SUCCEEDED',
                       'FAILED',
                       'STALE_PREVIEW',
                       'CONFLICTED'
                )
            ),

    CONSTRAINT chk_student_progression_operation_terminal_metadata
        CHECK (
            (
                status IN (
                           'SUCCEEDED',
                           'FAILED',
                           'STALE_PREVIEW',
                           'CONFLICTED'
                    )
                    AND completed_at IS NOT NULL
                )
                OR
            (
                status IN (
                           'PENDING',
                           'RUNNING'
                    )
                    AND completed_at IS NULL
                )
            ),

    CONSTRAINT chk_student_progression_operation_result_metadata
        CHECK (
            (
                status = 'SUCCEEDED'
                    AND result_json IS NOT NULL
                    AND failure_code IS NULL
                    AND failure_message IS NULL
                )
                OR
            (
                status <> 'SUCCEEDED'
                    AND result_json IS NULL
                )
            ),

    CONSTRAINT fk_student_progression_operation_source_year
        FOREIGN KEY (
                     source_academic_year_id,
                     organization_id
            )
            REFERENCES academic_years (
                                       id,
                                       organization_id
                )
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_progression_operation_target_year
        FOREIGN KEY (
                     target_academic_year_id,
                     organization_id
            )
            REFERENCES academic_years (
                                       id,
                                       organization_id
                )
            ON DELETE RESTRICT
);


/*
 * One row represents the final decision for one source enrollment.
 *
 * MANUAL_REVIEW is intentionally excluded because it blocks
 * confirmation and must not mutate or permanently process enrollment.
 */
CREATE TABLE student_progression_items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    source_enrollment_id BIGINT NOT NULL,
    student_user_id BIGINT NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    target_enrollment_id BIGINT,
    effective_on DATE NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_progression_item_source_enrollment
        UNIQUE (
                organization_id,
                source_enrollment_id
            ),

    CONSTRAINT uk_student_progression_item_target_enrollment
        UNIQUE (
                organization_id,
                target_enrollment_id
            ),

    CONSTRAINT chk_student_progression_item_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_student_progression_item_source_enrollment_positive
        CHECK (source_enrollment_id > 0),

    CONSTRAINT chk_student_progression_item_student_user_positive
        CHECK (student_user_id > 0),

    CONSTRAINT chk_student_progression_item_target_enrollment_positive
        CHECK (
            target_enrollment_id IS NULL
                OR target_enrollment_id > 0
            ),

    CONSTRAINT chk_student_progression_item_outcome
        CHECK (
            outcome IN (
                        'PROMOTED',
                        'REPEATED',
                        'GRADUATED',
                        'LEFT'
                )
            ),

    CONSTRAINT chk_student_progression_item_target_requirement
        CHECK (
            (
                outcome IN (
                            'PROMOTED',
                            'REPEATED'
                    )
                    AND target_enrollment_id IS NOT NULL
                )
                OR
            (
                outcome IN (
                            'GRADUATED',
                            'LEFT'
                    )
                    AND target_enrollment_id IS NULL
                )
            ),

    CONSTRAINT fk_student_progression_item_operation
        FOREIGN KEY (
                     operation_id,
                     organization_id
            )
            REFERENCES student_progression_operations (
                                                       id,
                                                       organization_id
                )
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_progression_item_source_enrollment
        FOREIGN KEY (
                     source_enrollment_id,
                     organization_id
            )
            REFERENCES student_enrollments (
                                            id,
                                            organization_id
                )
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_progression_item_target_enrollment
        FOREIGN KEY (
                     target_enrollment_id,
                     organization_id
            )
            REFERENCES student_enrollments (
                                            id,
                                            organization_id
                )
            ON DELETE RESTRICT
);


CREATE INDEX idx_student_progression_operation_target_status
    ON student_progression_operations (
                                       organization_id,
                                       target_academic_year_id,
                                       status
        );

CREATE INDEX idx_student_progression_operation_source_target
    ON student_progression_operations (
                                       organization_id,
                                       source_academic_year_id,
                                       target_academic_year_id
        );

CREATE INDEX idx_student_progression_operation_user_created
    ON student_progression_operations (
                                       organization_id,
                                       requested_by_user_id,
                                       created_at
        );

CREATE INDEX idx_student_progression_item_operation
    ON student_progression_items (
                                  organization_id,
                                  operation_id
        );

CREATE INDEX idx_student_progression_item_student_history
    ON student_progression_items (
                                  organization_id,
                                  student_user_id,
                                  created_at
        );