CREATE TABLE student_attendance_policies
(
    organization_id BIGINT PRIMARY KEY,
    attendance_mode VARCHAR(30) NOT NULL,
    week_start_day VARCHAR(20) NOT NULL,
    draft_warning_minutes INTEGER NOT NULL,
    automatic_submission_minutes INTEGER NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_student_attendance_policy_positive_ids
        CHECK (
            organization_id > 0
            AND created_by_user_id > 0
            AND updated_by_user_id > 0
        ),

    CONSTRAINT chk_student_attendance_policy_mode
        CHECK (attendance_mode IN ('DAILY')),

    CONSTRAINT chk_student_attendance_policy_week_start
        CHECK (
            week_start_day IN (
                'MONDAY',
                'TUESDAY',
                'WEDNESDAY',
                'THURSDAY',
                'FRIDAY',
                'SATURDAY',
                'SUNDAY'
            )
        ),

    CONSTRAINT chk_student_attendance_policy_minutes
        CHECK (
            draft_warning_minutes > 0
            AND draft_warning_minutes <= 240
            AND automatic_submission_minutes > draft_warning_minutes
            AND automatic_submission_minutes <= 480
        ),

    CONSTRAINT chk_student_attendance_policy_version
        CHECK (version >= 0)
);

CREATE TABLE student_attendance_status_policies
(
    organization_id BIGINT NOT NULL,
    attendance_status VARCHAR(30) NOT NULL,
    earned_credit NUMERIC(4,2) NOT NULL,
    possible_credit NUMERIC(4,2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (organization_id, attendance_status),

    CONSTRAINT chk_student_attendance_status_policy_status
        CHECK (
            attendance_status IN (
                'PRESENT',
                'ABSENT',
                'LATE',
                'HALF_DAY',
                'EXCUSED'
            )
        ),

    CONSTRAINT chk_student_attendance_status_policy_credits
        CHECK (
            earned_credit >= 0.00
            AND earned_credit <= 1.00
            AND possible_credit >= 0.00
            AND possible_credit <= 1.00
            AND earned_credit <= possible_credit
            AND (
                possible_credit <> 0.00
                OR earned_credit = 0.00
            )
        ),

    CONSTRAINT chk_student_attendance_status_policy_version
        CHECK (version >= 0),

    CONSTRAINT fk_student_attendance_status_policy_policy
        FOREIGN KEY (organization_id)
            REFERENCES student_attendance_policies (organization_id)
            ON DELETE RESTRICT
);

CREATE TABLE academic_calendar_days
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    calendar_date DATE NOT NULL,
    day_type VARCHAR(40) NOT NULL,
    name VARCHAR(150),
    attendance_requirement VARCHAR(30) NOT NULL,
    counts_toward_percentage BOOLEAN NOT NULL,
    day_weight NUMERIC(4,2) NOT NULL,
    note VARCHAR(500),
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_academic_calendar_day_date
        UNIQUE (
            organization_id,
            academic_year_id,
            calendar_date
        ),

    CONSTRAINT chk_academic_calendar_day_positive_ids
        CHECK (
            organization_id > 0
            AND academic_year_id > 0
            AND created_by_user_id > 0
            AND updated_by_user_id > 0
        ),

    CONSTRAINT chk_academic_calendar_day_type
        CHECK (
            day_type IN (
                'WORKING_DAY',
                'WEEKLY_OFF',
                'HOLIDAY',
                'VACATION',
                'SPECIAL_WORKING_DAY',
                'EXAM_DAY',
                'SPECIAL_FUNCTION'
            )
        ),

    CONSTRAINT chk_academic_calendar_attendance_requirement
        CHECK (
            attendance_requirement IN (
                'REQUIRED',
                'OPTIONAL',
                'NOT_APPLICABLE'
            )
        ),

    CONSTRAINT chk_academic_calendar_day_weight
        CHECK (day_weight >= 0.00 AND day_weight <= 1.00),

    CONSTRAINT chk_academic_calendar_day_counting
        CHECK (
            (
                counts_toward_percentage = FALSE
                AND day_weight = 0.00
            )
            OR
            (
                counts_toward_percentage = TRUE
                AND attendance_requirement = 'REQUIRED'
                AND day_weight > 0.00
            )
        ),

    CONSTRAINT chk_academic_calendar_day_requirement_rules
        CHECK (
            (
                attendance_requirement = 'NOT_APPLICABLE'
                AND counts_toward_percentage = FALSE
                AND day_weight = 0.00
            )
            OR attendance_requirement <> 'NOT_APPLICABLE'
        ),

    CONSTRAINT chk_academic_calendar_day_optional_rules
        CHECK (
            (
                attendance_requirement = 'OPTIONAL'
                AND counts_toward_percentage = FALSE
                AND day_weight = 0.00
            )
            OR attendance_requirement <> 'OPTIONAL'
        ),

    CONSTRAINT chk_academic_calendar_day_type_rules
        CHECK (
            (
                day_type IN ('WEEKLY_OFF', 'HOLIDAY', 'VACATION')
                AND attendance_requirement = 'NOT_APPLICABLE'
            )
            OR
            (
                day_type IN ('WORKING_DAY', 'SPECIAL_WORKING_DAY')
                AND attendance_requirement = 'REQUIRED'
            )
            OR
            (
                day_type = 'EXAM_DAY'
                AND attendance_requirement IN (
                    'REQUIRED',
                    'OPTIONAL',
                    'NOT_APPLICABLE'
                )
            )
            OR
            (
                day_type = 'SPECIAL_FUNCTION'
                AND attendance_requirement IN (
                    'REQUIRED',
                    'OPTIONAL',
                    'NOT_APPLICABLE'
                )
            )
        ),

    CONSTRAINT chk_academic_calendar_day_name_not_blank
        CHECK (name IS NULL OR BTRIM(name) <> ''),

    CONSTRAINT chk_academic_calendar_day_note_not_blank
        CHECK (note IS NULL OR BTRIM(note) <> ''),

    CONSTRAINT chk_academic_calendar_day_version
        CHECK (version >= 0),

    CONSTRAINT fk_academic_calendar_day_academic_year
        FOREIGN KEY (academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT
);

CREATE INDEX idx_academic_calendar_day_requirement
    ON academic_calendar_days (
        organization_id,
        academic_year_id,
        attendance_requirement,
        counts_toward_percentage
    );
