ALTER TABLE academic_calendar_days
    ADD CONSTRAINT uk_academic_calendar_day_id_org_year_date
        UNIQUE (id, organization_id, academic_year_id, calendar_date);

ALTER TABLE student_enrollments
    ADD CONSTRAINT uk_student_enrollment_id_student_section_grade_year_org
        UNIQUE (
            id,
            student_user_id,
            section_id,
            grade_level_id,
            academic_year_id,
            organization_id
        );

CREATE TABLE student_attendance_sessions
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id          BIGINT NOT NULL,
    academic_year_id         BIGINT NOT NULL,
    grade_level_id           BIGINT NOT NULL,
    section_id               BIGINT NOT NULL,
    academic_calendar_day_id BIGINT NOT NULL,
    attendance_date          DATE NOT NULL,
    lifecycle_status         VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    submission_type          VARCHAR(20),
    created_by_user_id       BIGINT NOT NULL,
    updated_by_user_id       BIGINT NOT NULL,
    submitted_by_user_id     BIGINT,
    submitted_at             TIMESTAMP WITH TIME ZONE,
    version                  BIGINT NOT NULL DEFAULT 0,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_attendance_session_section_date
        UNIQUE (organization_id, academic_year_id, section_id, attendance_date),

    CONSTRAINT uk_student_attendance_session_context
        UNIQUE (id, organization_id, academic_year_id, grade_level_id, section_id),

    CONSTRAINT chk_student_attendance_session_positive_ids
        CHECK (
            organization_id > 0
            AND academic_year_id > 0
            AND grade_level_id > 0
            AND section_id > 0
            AND academic_calendar_day_id > 0
            AND created_by_user_id > 0
            AND updated_by_user_id > 0
            AND (submitted_by_user_id IS NULL OR submitted_by_user_id > 0)
        ),

    CONSTRAINT chk_student_attendance_session_lifecycle
        CHECK (lifecycle_status IN ('DRAFT', 'SUBMITTED')),

    CONSTRAINT chk_student_attendance_session_submission_type
        CHECK (submission_type IS NULL OR submission_type IN ('MANUAL', 'AUTOMATIC')),

    CONSTRAINT chk_student_attendance_session_submission_metadata
        CHECK (
            (
                lifecycle_status = 'DRAFT'
                AND submission_type IS NULL
                AND submitted_by_user_id IS NULL
                AND submitted_at IS NULL
            )
            OR
            (
                lifecycle_status = 'SUBMITTED'
                AND submission_type = 'MANUAL'
                AND submitted_by_user_id IS NOT NULL
                AND submitted_at IS NOT NULL
            )
            OR
            (
                lifecycle_status = 'SUBMITTED'
                AND submission_type = 'AUTOMATIC'
                AND submitted_by_user_id IS NULL
                AND submitted_at IS NOT NULL
            )
        ),

    CONSTRAINT chk_student_attendance_session_version
        CHECK (version >= 0),

    CONSTRAINT fk_student_attendance_session_section
        FOREIGN KEY (section_id, grade_level_id, academic_year_id, organization_id)
            REFERENCES sections (id, grade_level_id, academic_year_id, organization_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_attendance_session_calendar_day
        FOREIGN KEY (academic_calendar_day_id, organization_id, academic_year_id, attendance_date)
            REFERENCES academic_calendar_days (id, organization_id, academic_year_id, calendar_date)
            ON DELETE RESTRICT
);

CREATE INDEX idx_student_attendance_session_section
    ON student_attendance_sessions (
        organization_id,
        academic_year_id,
        grade_level_id,
        section_id,
        attendance_date
    );

CREATE INDEX idx_student_attendance_session_lifecycle
    ON student_attendance_sessions (
        organization_id,
        academic_year_id,
        lifecycle_status,
        attendance_date
    );

CREATE TABLE student_attendance_records
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id        BIGINT NOT NULL,
    academic_year_id       BIGINT NOT NULL,
    grade_level_id         BIGINT NOT NULL,
    section_id             BIGINT NOT NULL,
    attendance_session_id  BIGINT NOT NULL,
    student_enrollment_id  BIGINT NOT NULL,
    student_user_id        BIGINT NOT NULL,
    recorded_status        VARCHAR(30) NOT NULL,
    effective_status       VARCHAR(30) NOT NULL,
    earned_credit          NUMERIC(4,2) NOT NULL,
    possible_credit        NUMERIC(4,2) NOT NULL,
    late_penalty_applied   BOOLEAN NOT NULL DEFAULT FALSE,
    remarks                VARCHAR(500),
    marked_by_user_id      BIGINT NOT NULL,
    updated_by_user_id     BIGINT NOT NULL,
    version                BIGINT NOT NULL DEFAULT 0,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_attendance_record_session_enrollment
        UNIQUE (attendance_session_id, student_enrollment_id),

    CONSTRAINT uk_student_attendance_record_session_student
        UNIQUE (attendance_session_id, student_user_id),

    CONSTRAINT chk_student_attendance_record_positive_ids
        CHECK (
            organization_id > 0
            AND academic_year_id > 0
            AND grade_level_id > 0
            AND section_id > 0
            AND attendance_session_id > 0
            AND student_enrollment_id > 0
            AND student_user_id > 0
            AND marked_by_user_id > 0
            AND updated_by_user_id > 0
        ),

    CONSTRAINT chk_student_attendance_record_status
        CHECK (
            recorded_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EXCUSED')
            AND effective_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EXCUSED')
        ),

    CONSTRAINT chk_student_attendance_record_credits
        CHECK (
            earned_credit >= 0.00
            AND earned_credit <= 1.00
            AND possible_credit >= 0.00
            AND possible_credit <= 1.00
            AND earned_credit <= possible_credit
            AND (possible_credit <> 0.00 OR earned_credit = 0.00)
        ),

    CONSTRAINT chk_student_attendance_record_late_penalty
        CHECK (
            (
                late_penalty_applied = TRUE
                AND recorded_status = 'LATE'
                AND effective_status IN ('HALF_DAY', 'ABSENT')
            )
            OR
            (
                late_penalty_applied = FALSE
                AND effective_status = recorded_status
            )
        ),

    CONSTRAINT chk_student_attendance_record_remarks
        CHECK (remarks IS NULL OR BTRIM(remarks) <> ''),

    CONSTRAINT chk_student_attendance_record_version
        CHECK (version >= 0),

    CONSTRAINT fk_student_attendance_record_session
        FOREIGN KEY (attendance_session_id, organization_id, academic_year_id, grade_level_id, section_id)
            REFERENCES student_attendance_sessions (id, organization_id, academic_year_id, grade_level_id, section_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_attendance_record_enrollment
        FOREIGN KEY (
            student_enrollment_id,
            student_user_id,
            section_id,
            grade_level_id,
            academic_year_id,
            organization_id
        )
            REFERENCES student_enrollments (
                id,
                student_user_id,
                section_id,
                grade_level_id,
                academic_year_id,
                organization_id
            )
            ON DELETE RESTRICT
);

CREATE INDEX idx_student_attendance_record_section_date_reporting
    ON student_attendance_records (
        organization_id,
        academic_year_id,
        grade_level_id,
        section_id,
        effective_status
    );

CREATE INDEX idx_student_attendance_record_student_history
    ON student_attendance_records (
        organization_id,
        student_user_id,
        academic_year_id,
        attendance_session_id
    );
