ALTER TABLE student_attendance_records
    ADD CONSTRAINT uk_student_attendance_record_id_session_context
        UNIQUE (
            id,
            organization_id,
            attendance_session_id,
            student_enrollment_id,
            student_user_id
        );

CREATE TABLE student_attendance_correction_requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    grade_level_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    attendance_session_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    reviewed_by_user_id BIGINT,
    review_comment VARCHAR(500),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_attendance_correction_request_item_context
        UNIQUE (id, organization_id, attendance_session_id),
    CONSTRAINT chk_student_attendance_correction_request_positive_ids
        CHECK (
            organization_id > 0
            AND academic_year_id > 0
            AND grade_level_id > 0
            AND section_id > 0
            AND attendance_session_id > 0
            AND requested_by_user_id > 0
            AND (reviewed_by_user_id IS NULL OR reviewed_by_user_id > 0)
        ),
    CONSTRAINT chk_student_attendance_correction_request_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_student_attendance_correction_request_reason
        CHECK (BTRIM(reason) <> ''),
    CONSTRAINT chk_student_attendance_correction_request_review_comment
        CHECK (review_comment IS NULL OR BTRIM(review_comment) <> ''),
    CONSTRAINT chk_student_attendance_correction_request_lifecycle
        CHECK (
            (
                status = 'PENDING'
                AND reviewed_by_user_id IS NULL
                AND reviewed_at IS NULL
                AND review_comment IS NULL
            )
            OR
            (
                status = 'CANCELLED'
                AND reviewed_by_user_id IS NULL
                AND reviewed_at IS NOT NULL
            )
            OR
            (
                status = 'APPROVED'
                AND reviewed_by_user_id IS NOT NULL
                AND reviewed_at IS NOT NULL
                AND reviewed_by_user_id <> requested_by_user_id
            )
            OR
            (
                status = 'REJECTED'
                AND reviewed_by_user_id IS NOT NULL
                AND reviewed_at IS NOT NULL
                AND reviewed_by_user_id <> requested_by_user_id
                AND review_comment IS NOT NULL
                AND BTRIM(review_comment) <> ''
            )
        ),
    CONSTRAINT chk_student_attendance_correction_request_version
        CHECK (version >= 0),
    CONSTRAINT fk_student_attendance_correction_request_session
        FOREIGN KEY (
            attendance_session_id,
            organization_id,
            academic_year_id,
            grade_level_id,
            section_id
        )
            REFERENCES student_attendance_sessions (
                id,
                organization_id,
                academic_year_id,
                grade_level_id,
                section_id
            )
            ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_student_attendance_correction_pending_session
    ON student_attendance_correction_requests (
        organization_id,
        attendance_session_id
    )
    WHERE status = 'PENDING';

CREATE INDEX idx_student_attendance_correction_request_session
    ON student_attendance_correction_requests (
        organization_id,
        attendance_session_id,
        status,
        requested_at DESC,
        id DESC
    );

CREATE INDEX idx_student_attendance_correction_request_section
    ON student_attendance_correction_requests (
        organization_id,
        academic_year_id,
        grade_level_id,
        section_id,
        status,
        requested_at DESC,
        id DESC
    );

CREATE TABLE student_attendance_correction_items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    correction_request_id BIGINT NOT NULL,
    attendance_session_id BIGINT NOT NULL,
    attendance_record_id BIGINT NOT NULL,
    student_enrollment_id BIGINT NOT NULL,
    student_user_id BIGINT NOT NULL,
    expected_attendance_record_version BIGINT NOT NULL,
    previous_recorded_status VARCHAR(30) NOT NULL,
    previous_effective_status VARCHAR(30) NOT NULL,
    previous_earned_credit NUMERIC(4,2) NOT NULL,
    previous_possible_credit NUMERIC(4,2) NOT NULL,
    previous_late_penalty_applied BOOLEAN NOT NULL,
    previous_remarks VARCHAR(500),
    proposed_recorded_status VARCHAR(30) NOT NULL,
    proposed_effective_status VARCHAR(30) NOT NULL,
    proposed_earned_credit NUMERIC(4,2) NOT NULL,
    proposed_possible_credit NUMERIC(4,2) NOT NULL,
    proposed_late_penalty_applied BOOLEAN NOT NULL,
    proposed_remarks VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_attendance_correction_item_record
        UNIQUE (correction_request_id, attendance_record_id),
    CONSTRAINT uk_student_attendance_correction_item_context
        UNIQUE (
            correction_request_id,
            organization_id,
            attendance_session_id,
            attendance_record_id,
            student_enrollment_id,
            student_user_id
        ),
    CONSTRAINT chk_student_attendance_correction_item_positive_ids
        CHECK (
            organization_id > 0
            AND correction_request_id > 0
            AND attendance_session_id > 0
            AND attendance_record_id > 0
            AND student_enrollment_id > 0
            AND student_user_id > 0
        ),
    CONSTRAINT chk_student_attendance_correction_item_expected_version
        CHECK (expected_attendance_record_version >= 0),
    CONSTRAINT chk_student_attendance_correction_item_status
        CHECK (
            previous_recorded_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EXCUSED')
            AND previous_effective_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EXCUSED')
            AND proposed_recorded_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EXCUSED')
            AND proposed_effective_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EXCUSED')
        ),
    CONSTRAINT chk_student_attendance_correction_item_previous_credits
        CHECK (
            previous_earned_credit >= 0.00
            AND previous_earned_credit <= 1.00
            AND previous_possible_credit >= 0.00
            AND previous_possible_credit <= 1.00
            AND previous_earned_credit <= previous_possible_credit
            AND (previous_possible_credit <> 0.00 OR previous_earned_credit = 0.00)
        ),
    CONSTRAINT chk_student_attendance_correction_item_proposed_credits
        CHECK (
            proposed_earned_credit >= 0.00
            AND proposed_earned_credit <= 1.00
            AND proposed_possible_credit >= 0.00
            AND proposed_possible_credit <= 1.00
            AND proposed_earned_credit <= proposed_possible_credit
            AND (proposed_possible_credit <> 0.00 OR proposed_earned_credit = 0.00)
        ),
    CONSTRAINT chk_student_attendance_correction_item_previous_late_penalty
        CHECK (
            (
                previous_late_penalty_applied = TRUE
                AND previous_recorded_status = 'LATE'
                AND previous_effective_status IN ('HALF_DAY', 'ABSENT')
            )
            OR
            (
                previous_late_penalty_applied = FALSE
                AND previous_effective_status = previous_recorded_status
            )
        ),
    CONSTRAINT chk_student_attendance_correction_item_proposed_late_penalty
        CHECK (
            (
                proposed_late_penalty_applied = TRUE
                AND proposed_recorded_status = 'LATE'
                AND proposed_effective_status IN ('HALF_DAY', 'ABSENT')
            )
            OR
            (
                proposed_late_penalty_applied = FALSE
                AND proposed_effective_status = proposed_recorded_status
            )
        ),
    CONSTRAINT chk_student_attendance_correction_item_remarks
        CHECK (
            (previous_remarks IS NULL OR BTRIM(previous_remarks) <> '')
            AND (proposed_remarks IS NULL OR BTRIM(proposed_remarks) <> '')
        ),
    CONSTRAINT chk_student_attendance_correction_item_changes_snapshot
        CHECK (
            proposed_recorded_status <> previous_recorded_status
            OR proposed_effective_status <> previous_effective_status
            OR proposed_earned_credit <> previous_earned_credit
            OR proposed_possible_credit <> previous_possible_credit
            OR proposed_late_penalty_applied <> previous_late_penalty_applied
            OR proposed_remarks IS DISTINCT FROM previous_remarks
        ),
    CONSTRAINT fk_student_attendance_correction_item_request
        FOREIGN KEY (correction_request_id)
            REFERENCES student_attendance_correction_requests (id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_student_attendance_correction_item_request_context
        FOREIGN KEY (
            correction_request_id,
            organization_id,
            attendance_session_id
        )
            REFERENCES student_attendance_correction_requests (
                id,
                organization_id,
                attendance_session_id
            )
            ON DELETE RESTRICT,
    CONSTRAINT fk_student_attendance_correction_item_record
        FOREIGN KEY (
            attendance_record_id,
            organization_id,
            attendance_session_id,
            student_enrollment_id,
            student_user_id
        )
            REFERENCES student_attendance_records (
                id,
                organization_id,
                attendance_session_id,
                student_enrollment_id,
                student_user_id
            )
            ON DELETE RESTRICT
);

CREATE INDEX idx_student_attendance_correction_item_request
    ON student_attendance_correction_items (
        organization_id,
        correction_request_id,
        attendance_record_id
    );
