CREATE TABLE student_attendance_offline_sync_operations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    grade_level_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(71) NOT NULL,
    sync_mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attendance_session_id BIGINT,
    failure_category VARCHAR(30),
    failure_message VARCHAR(500),
    result_json JSONB,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_attendance_offline_sync_actor_key
        UNIQUE (organization_id, actor_user_id, idempotency_key),
    CONSTRAINT chk_student_attendance_offline_sync_positive_ids
        CHECK (
            organization_id > 0
            AND actor_user_id > 0
            AND academic_year_id > 0
            AND grade_level_id > 0
            AND section_id > 0
            AND (attendance_session_id IS NULL OR attendance_session_id > 0)
        ),
    CONSTRAINT chk_student_attendance_offline_sync_hash
        CHECK (request_hash ~ '^sha256:[0-9a-f]{64}$'),
    CONSTRAINT chk_student_attendance_offline_sync_mode
        CHECK (sync_mode IN ('PARTIAL', 'COMPLETE')),
    CONSTRAINT chk_student_attendance_offline_sync_status
        CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT chk_student_attendance_offline_sync_failure_category
        CHECK (
            failure_category IS NULL
            OR failure_category IN ('VALIDATION', 'CONFLICT', 'FORBIDDEN', 'UNAVAILABLE')
        ),
    CONSTRAINT chk_student_attendance_offline_sync_lifecycle
        CHECK (
            (
                status = 'RUNNING'
                AND completed_at IS NULL
                AND result_json IS NULL
                AND failure_category IS NULL
                AND failure_message IS NULL
            )
            OR
            (
                status = 'SUCCEEDED'
                AND completed_at IS NOT NULL
                AND attendance_session_id IS NOT NULL
                AND result_json IS NOT NULL
                AND failure_category IS NULL
                AND failure_message IS NULL
            )
            OR
            (
                status = 'FAILED'
                AND completed_at IS NOT NULL
                AND result_json IS NULL
                AND failure_category IS NOT NULL
                AND failure_message IS NOT NULL
                AND BTRIM(failure_message) <> ''
            )
        ),
    CONSTRAINT chk_student_attendance_offline_sync_version
        CHECK (version >= 0),
    CONSTRAINT fk_student_attendance_offline_sync_academic_year
        FOREIGN KEY (academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_student_attendance_offline_sync_section
        FOREIGN KEY (
            section_id,
            grade_level_id,
            academic_year_id,
            organization_id
        )
            REFERENCES sections (
                id,
                grade_level_id,
                academic_year_id,
                organization_id
            )
            ON DELETE RESTRICT,
    CONSTRAINT fk_student_attendance_offline_sync_session
        FOREIGN KEY (
            attendance_session_id,
            organization_id,
            academic_year_id,
            grade_level_id,
            section_id
        )
            REFERENCES student_attendance_sessions (
                id,
                organization_id,
                academic_year_id,
                grade_level_id,
                section_id
            )
            ON DELETE RESTRICT
);

CREATE INDEX idx_student_attendance_offline_sync_context
    ON student_attendance_offline_sync_operations (
        organization_id,
        academic_year_id,
        grade_level_id,
        section_id,
        attendance_date,
        created_at DESC
    );
