ALTER TABLE student_attendance_offline_sync_operations
    ADD CONSTRAINT uk_student_attendance_offline_sync_id_org_actor
        UNIQUE (id, organization_id, actor_user_id);

CREATE TABLE student_attendance_import_previews
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    academic_year_id BIGINT,
    grade_level_id BIGINT,
    section_id BIGINT,
    attendance_date DATE,
    preview_fingerprint VARCHAR(71) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    source_format VARCHAR(10) NOT NULL,
    row_count INTEGER NOT NULL,
    can_confirm BOOLEAN NOT NULL,
    payload_json JSONB NOT NULL,
    confirmed_sync_operation_id BIGINT,
    confirmed_idempotency_key VARCHAR(128),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_student_attendance_import_preview_positive_ids
        CHECK (
            organization_id > 0
            AND actor_user_id > 0
            AND (academic_year_id IS NULL OR academic_year_id > 0)
            AND (grade_level_id IS NULL OR grade_level_id > 0)
            AND (section_id IS NULL OR section_id > 0)
            AND (confirmed_sync_operation_id IS NULL OR confirmed_sync_operation_id > 0)
        ),
    CONSTRAINT chk_student_attendance_import_preview_fingerprint
        CHECK (preview_fingerprint ~ '^sha256:[0-9a-f]{64}$'),
    CONSTRAINT chk_student_attendance_import_preview_format
        CHECK (source_format IN ('CSV', 'XLSX')),
    CONSTRAINT chk_student_attendance_import_preview_rows
        CHECK (row_count >= 1 AND row_count <= 100),
    CONSTRAINT chk_student_attendance_import_preview_context
        CHECK (
            can_confirm = FALSE
            OR (
                academic_year_id IS NOT NULL
                AND grade_level_id IS NOT NULL
                AND section_id IS NOT NULL
                AND attendance_date IS NOT NULL
            )
        ),
    CONSTRAINT chk_student_attendance_import_preview_confirmation
        CHECK (
            (
                confirmed_sync_operation_id IS NULL
                AND confirmed_idempotency_key IS NULL
            )
            OR (
                confirmed_sync_operation_id IS NULL
                AND confirmed_idempotency_key IS NOT NULL
                AND BTRIM(confirmed_idempotency_key) <> ''
            )
            OR (
                confirmed_sync_operation_id IS NOT NULL
                AND confirmed_idempotency_key IS NOT NULL
                AND BTRIM(confirmed_idempotency_key) <> ''
                AND can_confirm = TRUE
            )
        ),
    CONSTRAINT chk_student_attendance_import_preview_version
        CHECK (version >= 0),
    CONSTRAINT fk_student_attendance_import_preview_academic_year
        FOREIGN KEY (academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_student_attendance_import_preview_section
        FOREIGN KEY (section_id, grade_level_id, academic_year_id, organization_id)
            REFERENCES sections (id, grade_level_id, academic_year_id, organization_id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_student_attendance_import_preview_sync_operation
        FOREIGN KEY (confirmed_sync_operation_id, organization_id, actor_user_id)
            REFERENCES student_attendance_offline_sync_operations (id, organization_id, actor_user_id)
            ON DELETE RESTRICT
);

CREATE INDEX idx_student_attendance_import_preview_expiry
    ON student_attendance_import_previews (
        organization_id,
        actor_user_id,
        expires_at
    );
