/*
 * Durable transactional outbox for student-attendance notifications.
 *
 * academic-service only creates events. Email, SMS and WhatsApp delivery
 * belong to a downstream notification service.
 */

ALTER TABLE student_attendance_records
    ADD CONSTRAINT uk_student_attendance_record_outbox_context
        UNIQUE (
                id,
                organization_id,
                academic_year_id,
                grade_level_id,
                section_id,
                attendance_session_id,
                student_enrollment_id,
                student_user_id
            );

ALTER TABLE student_attendance_correction_requests
    ADD CONSTRAINT uk_student_attendance_correction_request_outbox_context
        UNIQUE (
                id,
                organization_id,
                attendance_session_id
            );

CREATE TABLE student_attendance_notification_outbox
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,

    organization_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    grade_level_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    attendance_session_id BIGINT NOT NULL,
    attendance_record_id BIGINT NOT NULL,
    correction_request_id BIGINT,

    student_enrollment_id BIGINT NOT NULL,
    student_user_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,

    event_type VARCHAR(50) NOT NULL,
    event_source VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    payload JSONB NOT NULL,

    publication_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),

    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
                                            DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                                            DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_student_attendance_notification_outbox_event
        UNIQUE (event_id),

    CONSTRAINT uk_student_attendance_notification_outbox_idempotency
        UNIQUE (organization_id, idempotency_key),

    CONSTRAINT chk_student_attendance_notification_outbox_ids
        CHECK (
            organization_id > 0
                AND academic_year_id > 0
                AND grade_level_id > 0
                AND section_id > 0
                AND attendance_session_id > 0
                AND attendance_record_id > 0
                AND student_enrollment_id > 0
                AND student_user_id > 0
                AND (
                correction_request_id IS NULL
                    OR correction_request_id > 0
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_type
        CHECK (
            event_type IN (
                           'ABSENCE_RECORDED',
                           'LATE_RECORDED',
                           'LATE_PENALTY_APPLIED',
                           'ATTENDANCE_ALERT_CLEARED'
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_source
        CHECK (
            event_source IN (
                             'MANUAL_SUBMISSION',
                             'AUTOMATIC_SUBMISSION',
                             'CORRECTION_APPROVAL'
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_correction
        CHECK (
            (
                event_source = 'CORRECTION_APPROVAL'
                    AND correction_request_id IS NOT NULL
                )
                OR
            (
                event_source <> 'CORRECTION_APPROVAL'
                    AND correction_request_id IS NULL
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_status
        CHECK (
            publication_status IN (
                                   'PENDING',
                                   'PUBLISHED',
                                   'DEAD_LETTER'
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_delivery
        CHECK (
            attempt_count >= 0
                AND (
                (
                    publication_status = 'PENDING'
                        AND published_at IS NULL
                    )
                    OR
                (
                    publication_status = 'PUBLISHED'
                        AND published_at IS NOT NULL
                    )
                    OR
                (
                    publication_status = 'DEAD_LETTER'
                        AND published_at IS NULL
                        AND last_error IS NOT NULL
                        AND BTRIM(last_error) <> ''
                    )
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_text
        CHECK (
            BTRIM(idempotency_key) <> ''
                AND (
                last_error IS NULL
                    OR BTRIM(last_error) <> ''
                )
            ),

    CONSTRAINT chk_student_attendance_notification_outbox_payload
        CHECK (JSONB_TYPEOF(payload) = 'object'),

    CONSTRAINT chk_student_attendance_notification_outbox_version
        CHECK (version >= 0),

    CONSTRAINT fk_student_attendance_notification_outbox_record
        FOREIGN KEY (
                     attendance_record_id,
                     organization_id,
                     academic_year_id,
                     grade_level_id,
                     section_id,
                     attendance_session_id,
                     student_enrollment_id,
                     student_user_id
            )
            REFERENCES student_attendance_records (
                                                   id,
                                                   organization_id,
                                                   academic_year_id,
                                                   grade_level_id,
                                                   section_id,
                                                   attendance_session_id,
                                                   student_enrollment_id,
                                                   student_user_id
                )
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_attendance_notification_outbox_correction
        FOREIGN KEY (
                     correction_request_id,
                     organization_id,
                     attendance_session_id
            )
            REFERENCES student_attendance_correction_requests (
                                                               id,
                                                               organization_id,
                                                               attendance_session_id
                )
            ON DELETE RESTRICT
);

CREATE INDEX idx_student_attendance_notification_outbox_pending
    ON student_attendance_notification_outbox (
                                               publication_status,
                                               available_at,
                                               id
        )
    WHERE publication_status = 'PENDING';

CREATE INDEX idx_student_attendance_notification_outbox_student
    ON student_attendance_notification_outbox (
                                               organization_id,
                                               student_user_id,
                                               attendance_date,
                                               id
        );
