CREATE TABLE examinations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT       NOT NULL,
    academic_year_id BIGINT       NOT NULL,
    name             VARCHAR(120) NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    published_at     TIMESTAMP WITH TIME ZONE,
    version          BIGINT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_examination_organization_positive CHECK (organization_id > 0),
    CONSTRAINT chk_examination_year_positive CHECK (academic_year_id > 0),
    CONSTRAINT chk_examination_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT chk_examination_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    CONSTRAINT chk_examination_published_at
        CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CONSTRAINT uk_examination_id_year_organization
        UNIQUE (id, academic_year_id, organization_id),
    CONSTRAINT fk_examination_academic_year
        FOREIGN KEY (academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_examination_year_name_ci
    ON examinations (academic_year_id, LOWER(name));

CREATE INDEX idx_examination_organization_year_status
    ON examinations (organization_id, academic_year_id, status);
