CREATE TABLE academic_years
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id	BIGINT NOT NULL,
    name	VARCHAR(50) NOT NULL,
    start_date	DATE NOT NULL ,
    end_date	DATE NOT NULL ,
    status	VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    version	BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_academic_year_organization_name
        UNIQUE (organization_id, name),

    CONSTRAINT chk_academic_year_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_academic_year_dates
        CHECK (start_date < end_date),

    CONSTRAINT chk_academic_year_status
        CHECK (status IN ('PLANNED', 'ACTIVE', 'CLOSED'))
);

CREATE UNIQUE INDEX uk_academic_year_one_active_per_organization
    ON academic_years (organization_id)
    WHERE status = 'ACTIVE';
