CREATE TABLE scheduled_assessments
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id        BIGINT        NOT NULL,
    academic_year_id       BIGINT        NOT NULL,
    examination_id         BIGINT        NOT NULL,
    grade_level_id         BIGINT        NOT NULL,
    grade_level_subject_id BIGINT        NOT NULL,
    assessment_date        DATE          NOT NULL,
    start_time             TIME          NOT NULL,
    end_time               TIME          NOT NULL,
    maximum_marks          NUMERIC(7, 2) NOT NULL,
    version                BIGINT        NOT NULL DEFAULT 0,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_assessment_organization_positive CHECK (organization_id > 0),
    CONSTRAINT chk_assessment_year_positive CHECK (academic_year_id > 0),
    CONSTRAINT chk_assessment_exam_positive CHECK (examination_id > 0),
    CONSTRAINT chk_assessment_grade_positive CHECK (grade_level_id > 0),
    CONSTRAINT chk_assessment_subject_positive CHECK (grade_level_subject_id > 0),
    CONSTRAINT chk_assessment_time_order CHECK (start_time < end_time),
    CONSTRAINT chk_assessment_maximum_marks CHECK (maximum_marks > 0),
    CONSTRAINT uk_assessment_exam_grade_subject
        UNIQUE (examination_id, grade_level_subject_id),
    CONSTRAINT fk_assessment_examination
        FOREIGN KEY (examination_id, academic_year_id, organization_id)
            REFERENCES examinations (id, academic_year_id, organization_id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_assessment_grade_subject
        FOREIGN KEY (
            grade_level_subject_id, grade_level_id,
            academic_year_id, organization_id
        )
            REFERENCES grade_level_subjects (
                id, grade_level_id, academic_year_id, organization_id
            )
            ON DELETE RESTRICT
);

CREATE INDEX idx_assessment_organization_year_grade_date
    ON scheduled_assessments (
        organization_id, academic_year_id, grade_level_id,
        assessment_date, start_time
    );
