/*
 * Enables a tenant-safe composite foreign key from grade_levels.
 */
ALTER TABLE academic_years
    ADD CONSTRAINT uk_academic_year_id_organization
        UNIQUE (id, organization_id);


CREATE TABLE grade_levels
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT       NOT NULL,
    academic_year_id BIGINT       NOT NULL,
    code             VARCHAR(50)  NOT NULL,
    name             VARCHAR(100) NOT NULL,
    display_order    INTEGER      NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
                                           DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
                                           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_grade_level_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_grade_level_display_order_positive
        CHECK (display_order > 0),

    CONSTRAINT chk_grade_level_code_not_blank
        CHECK (BTRIM(code) <> ''),

    CONSTRAINT chk_grade_level_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT uk_grade_level_year_code
        UNIQUE (academic_year_id, code),

    CONSTRAINT uk_grade_level_year_display_order
        UNIQUE (academic_year_id, display_order),

    CONSTRAINT fk_grade_level_academic_year
        FOREIGN KEY (academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT
);


/*
 * Prevent names differing only by case, such as
 * "Class 10" and "class 10", within the same academic year.
 */
CREATE UNIQUE INDEX uk_grade_level_year_name_ci
    ON grade_levels (
                     academic_year_id,
                     LOWER(name)
        );


CREATE INDEX idx_grade_level_organization_year
    ON grade_levels (
                     organization_id,
                     academic_year_id
        );