/*
 * Enables a tenant-safe composite foreign key from sections.
 *
 * This guarantees that a section's grade level, academic year,
 * and organization belong to the same hierarchy.
 */
ALTER TABLE grade_levels
    ADD CONSTRAINT uk_grade_level_id_year_organization
        UNIQUE (
                id,
                academic_year_id,
                organization_id
            );


CREATE TABLE sections
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT       NOT NULL,
    academic_year_id  BIGINT       NOT NULL,
    grade_level_id    BIGINT       NOT NULL,
    code              VARCHAR(50)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    display_order     INTEGER      NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                            DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                            DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_section_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_section_academic_year_positive
        CHECK (academic_year_id > 0),

    CONSTRAINT chk_section_grade_level_positive
        CHECK (grade_level_id > 0),

    CONSTRAINT chk_section_display_order_positive
        CHECK (display_order > 0),

    CONSTRAINT chk_section_code_not_blank
        CHECK (BTRIM(code) <> ''),

    CONSTRAINT chk_section_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT uk_section_grade_level_code
        UNIQUE (
                grade_level_id,
                code
            ),

    CONSTRAINT uk_section_grade_level_display_order
        UNIQUE (
                grade_level_id,
                display_order
            ),

    CONSTRAINT fk_section_grade_level
        FOREIGN KEY (
                     grade_level_id,
                     academic_year_id,
                     organization_id
            )
            REFERENCES grade_levels (
                                     id,
                                     academic_year_id,
                                     organization_id
                )
            ON DELETE RESTRICT
);


/*
 * Prevent names that differ only by case within one grade level,
 * such as "Section A" and "section a".
 */
CREATE UNIQUE INDEX uk_section_grade_level_name_ci
    ON sections (
                 grade_level_id,
                 LOWER(name)
        );


/*
 * Supports tenant-safe listing of all sections belonging to a grade level.
 */
CREATE INDEX idx_section_organization_year_grade
    ON sections (
                 organization_id,
                 academic_year_id,
                 grade_level_id
        );