/*
 * Subjects are defined once within an academic year.
 *
 * A separate grade_level_subjects table will later assign
 * these subjects to one or more grade levels.
 */
CREATE TABLE subjects
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT       NOT NULL,
    academic_year_id  BIGINT       NOT NULL,
    code              VARCHAR(50)  NOT NULL,
    name              VARCHAR(120) NOT NULL,
    description       VARCHAR(500),
    version           BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                            DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                            DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_subject_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_subject_academic_year_positive
        CHECK (academic_year_id > 0),

    CONSTRAINT chk_subject_code_not_blank
        CHECK (BTRIM(code) <> ''),

    CONSTRAINT chk_subject_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT chk_subject_description_not_blank
        CHECK (
            description IS NULL
                OR BTRIM(description) <> ''
            ),

    CONSTRAINT fk_subject_academic_year
        FOREIGN KEY (
                     academic_year_id,
                     organization_id
            )
            REFERENCES academic_years (
                                       id,
                                       organization_id
                )
            ON DELETE RESTRICT,

    /*
     * Required later for a tenant-safe composite foreign key
     * from grade_level_subjects.
     */
    CONSTRAINT uk_subject_id_year_organization
        UNIQUE (
                id,
                academic_year_id,
                organization_id
            )
);


/*
 * Subject codes and names are unique within an academic year,
 * ignoring letter case.
 */
CREATE UNIQUE INDEX uk_subject_year_code_ci
    ON subjects (
                 academic_year_id,
                 LOWER(code)
        );

CREATE UNIQUE INDEX uk_subject_year_name_ci
    ON subjects (
                 academic_year_id,
                 LOWER(name)
        );


CREATE INDEX idx_subject_organization_year
    ON subjects (
                 organization_id,
                 academic_year_id
        );