/*
 * Connects reusable subjects to grade levels.
 *
 * Both foreign keys include organization_id and academic_year_id,
 * preventing cross-tenant and cross-year assignments.
 */
CREATE TABLE grade_level_subjects
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT  NOT NULL,
    academic_year_id  BIGINT  NOT NULL,
    grade_level_id    BIGINT  NOT NULL,
    subject_id        BIGINT  NOT NULL,
    mandatory         BOOLEAN NOT NULL DEFAULT TRUE,
    display_order     INTEGER NOT NULL,
    version           BIGINT  NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                       DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_grade_subject_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_grade_subject_academic_year_positive
        CHECK (academic_year_id > 0),

    CONSTRAINT chk_grade_subject_grade_level_positive
        CHECK (grade_level_id > 0),

    CONSTRAINT chk_grade_subject_subject_positive
        CHECK (subject_id > 0),

    CONSTRAINT chk_grade_subject_display_order_positive
        CHECK (display_order > 0),

    /*
     * The same subject can only be assigned once to one grade.
     */
    CONSTRAINT uk_grade_subject_assignment
        UNIQUE (
                grade_level_id,
                subject_id
            ),

    /*
     * Two subjects cannot occupy the same display position
     * within one grade.
     */
    CONSTRAINT uk_grade_subject_display_order
        UNIQUE (
                grade_level_id,
                display_order
            ),

    CONSTRAINT fk_grade_subject_grade_level
        FOREIGN KEY (
                     grade_level_id,
                     academic_year_id,
                     organization_id
            )
            REFERENCES grade_levels (
                                     id,
                                     academic_year_id,
                                     organization_id
                )
            ON DELETE RESTRICT,

    CONSTRAINT fk_grade_subject_subject
        FOREIGN KEY (
                     subject_id,
                     academic_year_id,
                     organization_id
            )
            REFERENCES subjects (
                                 id,
                                 academic_year_id,
                                 organization_id
                )
            ON DELETE RESTRICT
);


/*
 * Supports listing all subjects assigned to a grade.
 */
CREATE INDEX idx_grade_subject_organization_year_grade
    ON grade_level_subjects (
                             organization_id,
                             academic_year_id,
                             grade_level_id
        );


/*
 * Supports finding every grade that uses a subject.
 */
CREATE INDEX idx_grade_subject_organization_year_subject
    ON grade_level_subjects (
                             organization_id,
                             academic_year_id,
                             subject_id
        );