/*
 * Enables tenant-safe references from teacher_assignments.
 */
ALTER TABLE sections
    ADD CONSTRAINT uk_section_id_grade_year_organization
        UNIQUE (
                id,
                grade_level_id,
                academic_year_id,
                organization_id
            );

ALTER TABLE grade_level_subjects
    ADD CONSTRAINT uk_grade_subject_id_grade_year_organization
        UNIQUE (
                id,
                grade_level_id,
                academic_year_id,
                organization_id
            );


CREATE TABLE teacher_assignments
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id          BIGINT      NOT NULL,
    academic_year_id         BIGINT      NOT NULL,
    grade_level_id           BIGINT      NOT NULL,
    section_id               BIGINT      NOT NULL,
    grade_level_subject_id   BIGINT,
    teacher_user_id          BIGINT      NOT NULL,
    assignment_type          VARCHAR(30) NOT NULL,
    version                  BIGINT      NOT NULL DEFAULT 0,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL
                                                  DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL
                                                  DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_teacher_assignment_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_teacher_assignment_year_positive
        CHECK (academic_year_id > 0),

    CONSTRAINT chk_teacher_assignment_grade_positive
        CHECK (grade_level_id > 0),

    CONSTRAINT chk_teacher_assignment_section_positive
        CHECK (section_id > 0),

    CONSTRAINT chk_teacher_assignment_teacher_positive
        CHECK (teacher_user_id > 0),

    CONSTRAINT chk_teacher_assignment_type
        CHECK (
            assignment_type IN (
                                'CLASS_TEACHER',
                                'SUBJECT_TEACHER'
                )
            ),

    /*
     * Class teachers do not require a subject.
     * Subject teachers must reference a subject assigned to the grade.
     */
    CONSTRAINT chk_teacher_assignment_subject_requirement
        CHECK (
            (
                assignment_type = 'CLASS_TEACHER'
                    AND grade_level_subject_id IS NULL
                )
                OR
            (
                assignment_type = 'SUBJECT_TEACHER'
                    AND grade_level_subject_id IS NOT NULL
                    AND grade_level_subject_id > 0
                )
            ),

    CONSTRAINT fk_teacher_assignment_section
        FOREIGN KEY (
                     section_id,
                     grade_level_id,
                     academic_year_id,
                     organization_id
            )
            REFERENCES sections (
                                 id,
                                 grade_level_id,
                                 academic_year_id,
                                 organization_id
                )
            ON DELETE RESTRICT,

    CONSTRAINT fk_teacher_assignment_grade_subject
        FOREIGN KEY (
                     grade_level_subject_id,
                     grade_level_id,
                     academic_year_id,
                     organization_id
            )
            REFERENCES grade_level_subjects (
                                             id,
                                             grade_level_id,
                                             academic_year_id,
                                             organization_id
                )
            ON DELETE RESTRICT
);


/*
 * Initially, one section has one class teacher.
 */
CREATE UNIQUE INDEX uk_teacher_assignment_one_class_teacher
    ON teacher_assignments (section_id)
    WHERE assignment_type = 'CLASS_TEACHER';


/*
 * Initially, one section has one teacher for each assigned subject.
 */
CREATE UNIQUE INDEX uk_teacher_assignment_one_subject_teacher
    ON teacher_assignments (
                            section_id,
                            grade_level_subject_id
        )
    WHERE assignment_type = 'SUBJECT_TEACHER';


CREATE INDEX idx_teacher_assignment_organization_year_teacher
    ON teacher_assignments (
                            organization_id,
                            academic_year_id,
                            teacher_user_id
        );


CREATE INDEX idx_teacher_assignment_section
    ON teacher_assignments (
                            organization_id,
                            academic_year_id,
                            grade_level_id,
                            section_id
        );