CREATE TABLE student_enrollments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT      NOT NULL,
    academic_year_id  BIGINT      NOT NULL,
    grade_level_id    BIGINT      NOT NULL,
    section_id        BIGINT      NOT NULL,
    student_user_id   BIGINT      NOT NULL,
    roll_number       VARCHAR(30) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'ENROLLED',
    enrolled_on       DATE        NOT NULL,
    ended_on          DATE,
    version           BIGINT      NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                           DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
                                           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_student_enrollment_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_student_enrollment_year_positive
        CHECK (academic_year_id > 0),

    CONSTRAINT chk_student_enrollment_grade_positive
        CHECK (grade_level_id > 0),

    CONSTRAINT chk_student_enrollment_section_positive
        CHECK (section_id > 0),

    CONSTRAINT chk_student_enrollment_user_positive
        CHECK (student_user_id > 0),

    CONSTRAINT chk_student_enrollment_roll_not_blank
        CHECK (BTRIM(roll_number) <> ''),

    CONSTRAINT chk_student_enrollment_status
        CHECK (
            status IN (
                       'ENROLLED',
                       'TRANSFERRED',
                       'WITHDRAWN',
                       'COMPLETED'
                )
            ),

    /*
     * Active enrollment has no end date.
     * Historical enrollment must record when it ended.
     */
    CONSTRAINT chk_student_enrollment_end_date
        CHECK (
            (
                status = 'ENROLLED'
                    AND ended_on IS NULL
                )
                OR
            (
                status IN (
                           'TRANSFERRED',
                           'WITHDRAWN',
                           'COMPLETED'
                    )
                    AND ended_on IS NOT NULL
                    AND ended_on >= enrolled_on
                )
            ),

    CONSTRAINT fk_student_enrollment_section
        FOREIGN KEY (
                     section_id,
                     grade_level_id,
                     academic_year_id,
                     organization_id
            )
            REFERENCES sections (
                                 id,
                                 grade_level_id,
                                 academic_year_id,
                                 organization_id
                )
            ON DELETE RESTRICT
);


/*
 * A student can have only one current enrollment
 * within an academic year.
 */
CREATE UNIQUE INDEX uk_student_one_active_enrollment_per_year
    ON student_enrollments (
                            organization_id,
                            academic_year_id,
                            student_user_id
        )
    WHERE status = 'ENROLLED';


/*
 * Active roll numbers are unique within a section.
 * A historical transferred/withdrawn student does not permanently
 * block that roll number.
 */
CREATE UNIQUE INDEX uk_student_active_section_roll_ci
    ON student_enrollments (
                            organization_id,
                            academic_year_id,
                            section_id,
                            LOWER(roll_number)
        )
    WHERE status = 'ENROLLED';


/*
 * Supports class-list and attendance queries.
 */
CREATE INDEX idx_student_enrollment_section_status
    ON student_enrollments (
                            organization_id,
                            academic_year_id,
                            grade_level_id,
                            section_id,
                            status
        );


/*
 * Supports viewing a student's enrollment history.
 */
CREATE INDEX idx_student_enrollment_user_history
    ON student_enrollments (
                            organization_id,
                            student_user_id,
                            academic_year_id,
                            enrolled_on
        );
