CREATE TABLE academic_year_structure_rollover_operations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    source_academic_year_id BIGINT NOT NULL,
    target_academic_year_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(71) NOT NULL,
    preview_fingerprint VARCHAR(71) NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    failure_code VARCHAR(80),
    failure_message VARCHAR(500),
    result_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_rollover_operation_tenant_idempotency
        UNIQUE (organization_id, idempotency_key),

    CONSTRAINT chk_rollover_operation_organization_positive
        CHECK (organization_id > 0),

    CONSTRAINT chk_rollover_operation_source_year_positive
        CHECK (source_academic_year_id > 0),

    CONSTRAINT chk_rollover_operation_target_year_positive
        CHECK (target_academic_year_id > 0),

    CONSTRAINT chk_rollover_operation_user_positive
        CHECK (requested_by_user_id > 0),

    CONSTRAINT chk_rollover_operation_distinct_years
        CHECK (source_academic_year_id <> target_academic_year_id),

    CONSTRAINT chk_rollover_operation_hash_format
        CHECK (
            request_hash ~ '^sha256:[0-9a-f]{64}$'
                AND preview_fingerprint ~ '^sha256:[0-9a-f]{64}$'
        ),

    CONSTRAINT chk_rollover_operation_status
        CHECK (
            status IN (
                       'PENDING',
                       'RUNNING',
                       'SUCCEEDED',
                       'FAILED',
                       'STALE_PREVIEW',
                       'CONFLICTED'
                )
        ),

    CONSTRAINT chk_rollover_operation_terminal_metadata
        CHECK (
            (
                status IN (
                           'SUCCEEDED',
                           'FAILED',
                           'STALE_PREVIEW',
                           'CONFLICTED'
                    )
                    AND completed_at IS NOT NULL
                )
                OR
            (
                status IN ('PENDING', 'RUNNING')
                    AND completed_at IS NULL
                )
        ),

    CONSTRAINT chk_rollover_operation_result_metadata
        CHECK (
            (
                status = 'SUCCEEDED'
                    AND result_json IS NOT NULL
                    AND failure_code IS NULL
                    AND failure_message IS NULL
                )
                OR
            (
                status <> 'SUCCEEDED'
                    AND result_json IS NULL
                )
        ),

    CONSTRAINT fk_rollover_operation_source_year
        FOREIGN KEY (source_academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_rollover_operation_target_year
        FOREIGN KEY (target_academic_year_id, organization_id)
            REFERENCES academic_years (id, organization_id)
            ON DELETE RESTRICT
);

CREATE INDEX idx_rollover_operation_organization_target_status
    ON academic_year_structure_rollover_operations (
                                                    organization_id,
                                                    target_academic_year_id,
                                                    status
        );

CREATE INDEX idx_rollover_operation_organization_source_target
    ON academic_year_structure_rollover_operations (
                                                    organization_id,
                                                    source_academic_year_id,
                                                    target_academic_year_id
        );

CREATE INDEX idx_rollover_operation_organization_user_created
    ON academic_year_structure_rollover_operations (
                                                    organization_id,
                                                    requested_by_user_id,
                                                    created_at
        );
