CREATE TABLE platform_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255),

    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100),

    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_ACTIVATION',

    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    login_lock_level INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP WITH TIME ZONE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    password_changed_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_platform_users_username
        UNIQUE (username),

    CONSTRAINT uk_platform_users_email
        UNIQUE (email),

    CONSTRAINT chk_platform_users_failed_login_attempts
        CHECK (failed_login_attempts >= 0),

    CONSTRAINT chk_platform_users_login_lock_level
        CHECK (login_lock_level >= 0)
);

CREATE TABLE platform_user_roles (
     platform_user_id BIGINT NOT NULL,
     role VARCHAR(60) NOT NULL,

     CONSTRAINT pk_platform_user_roles
         PRIMARY KEY (platform_user_id, role),

     CONSTRAINT fk_platform_user_roles_user
         FOREIGN KEY (platform_user_id)
             REFERENCES platform_users(id)
             ON DELETE CASCADE
);

CREATE INDEX idx_platform_users_status
    ON platform_users(status);

CREATE INDEX idx_platform_users_phone
    ON platform_users(phone);

CREATE INDEX idx_platform_user_roles_role
    ON platform_user_roles(role);