CREATE TABLE platform_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    owning_service VARCHAR(100) NOT NULL,
    sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_platform_permissions_code UNIQUE (code)
);

CREATE TABLE platform_role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(100) NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_platform_role_permissions_role_permission
        UNIQUE (role, permission_id),
    CONSTRAINT fk_platform_role_permissions_permission
        FOREIGN KEY (permission_id)
            REFERENCES platform_permissions(id)
            ON DELETE CASCADE
);

CREATE INDEX idx_platform_role_permissions_role
    ON platform_role_permissions(role);

INSERT INTO platform_permissions (
    code,
    description,
    owning_service,
    sensitive
)
VALUES
('PLATFORM_PROFILE_VIEW_SELF', 'View own Dawnrise employee profile', 'identity-service', FALSE),
('PLATFORM_PROFILE_UPDATE_SELF', 'Update own Dawnrise employee profile', 'identity-service', FALSE),
('PLATFORM_PASSWORD_CHANGE_SELF', 'Change own Dawnrise employee password', 'identity-service', TRUE),
('PLATFORM_SESSION_VIEW_SELF', 'View own Dawnrise employee sessions', 'identity-service', FALSE),
('PLATFORM_SESSION_REVOKE_SELF', 'Revoke own Dawnrise employee sessions', 'identity-service', TRUE),
('PLATFORM_USER_CREATE', 'Create Dawnrise employee identities', 'identity-service', TRUE),
('PLATFORM_USER_VIEW', 'View Dawnrise employee identities', 'identity-service', TRUE),
('PLATFORM_USER_PROFILE_UPDATE', 'Update Dawnrise employee profile data', 'identity-service', TRUE),
('PLATFORM_USER_ACTIVATE', 'Resend Dawnrise employee activation invitations', 'identity-service', TRUE),
('PLATFORM_USER_DEACTIVATE', 'Deactivate Dawnrise employee identities', 'identity-service', TRUE),
('PLATFORM_USER_SUSPEND', 'Suspend Dawnrise employee identities', 'identity-service', TRUE),
('PLATFORM_USER_REACTIVATE', 'Reactivate Dawnrise employee identities', 'identity-service', TRUE),
('PLATFORM_USER_UNLOCK', 'Unlock Dawnrise employee identities', 'identity-service', TRUE),
('PLATFORM_ROLE_VIEW', 'View Dawnrise platform roles', 'identity-service', TRUE),
('PLATFORM_PERMISSION_VIEW', 'View Dawnrise platform permissions', 'identity-service', TRUE),
('PLATFORM_ROLE_ASSIGN', 'Assign Dawnrise platform roles', 'identity-service', TRUE),
('PLATFORM_ROLE_REMOVE', 'Remove Dawnrise platform roles', 'identity-service', TRUE),
('LEAD_VIEW', 'View leads and demo requests', 'identity-service', FALSE),
('LEAD_UPDATE', 'Update leads and demo requests', 'identity-service', FALSE),
('LEAD_ASSIGN', 'Assign leads and demo requests', 'identity-service', FALSE),
('ORGANIZATION_APPLICATION_VIEW', 'View institution applications', 'identity-service', FALSE),
('ORGANIZATION_APPLICATION_ASSIGN', 'Assign institution applications', 'identity-service', FALSE),
('ORGANIZATION_APPLICATION_REVIEW', 'Review institution applications', 'identity-service', FALSE),
('ORGANIZATION_APPLICATION_VERIFY', 'Verify institution application data', 'identity-service', FALSE),
('ORGANIZATION_APPLICATION_APPROVE', 'Approve institution applications', 'identity-service', TRUE),
('ORGANIZATION_APPLICATION_REJECT', 'Reject institution applications', 'identity-service', TRUE),
('ORGANIZATION_VIEW', 'View provisioned organizations', 'identity-service', FALSE),
('ORGANIZATION_CREATE', 'Create provisioned organizations', 'identity-service', TRUE),
('PROVISIONING_START', 'Start organization provisioning', 'identity-service', TRUE),
('PROVISIONING_VIEW', 'View organization provisioning status', 'identity-service', FALSE),
('PROVISIONING_RETRY', 'Retry organization provisioning', 'identity-service', TRUE),
('PLAN_VIEW', 'View plans', 'identity-service', FALSE),
('PLAN_ASSIGN', 'Assign plans', 'identity-service', TRUE),
('SUBSCRIPTION_VIEW', 'View subscriptions', 'identity-service', FALSE),
('SUBSCRIPTION_UPDATE', 'Update subscriptions', 'identity-service', TRUE),
('SUPPORT_ASSIGNMENT_CREATE', 'Create controlled support assignments', 'identity-service', TRUE),
('SUPPORT_ASSIGNMENT_VIEW', 'View controlled support assignments', 'identity-service', FALSE),
('SUPPORT_ASSIGNMENT_REVOKE', 'Revoke controlled support assignments', 'identity-service', TRUE),
('DATA_IMPORT_CREATE', 'Create approved data imports', 'identity-service', TRUE),
('DATA_IMPORT_VIEW', 'View data imports', 'identity-service', FALSE),
('DATA_IMPORT_VALIDATE', 'Validate data imports', 'identity-service', TRUE),
('DATA_IMPORT_EXECUTE', 'Execute approved data imports', 'identity-service', TRUE),
('PLATFORM_SECURITY_AUDIT_VIEW', 'View Dawnrise platform security audit events', 'identity-service', TRUE);

INSERT INTO platform_role_permissions (role, permission_id)
SELECT 'PLATFORM_SUPER_ADMIN', id
FROM platform_permissions
WHERE active = TRUE;

INSERT INTO platform_role_permissions (role, permission_id)
SELECT role_mapping.role, platform_permissions.id
FROM (
    VALUES
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_SESSION_VIEW_SELF'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_CREATE'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_VIEW'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_PROFILE_UPDATE'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_ACTIVATE'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_DEACTIVATE'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_SUSPEND'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_REACTIVATE'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_USER_UNLOCK'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_ROLE_VIEW'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_PERMISSION_VIEW'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_ROLE_ASSIGN'),
    ('PLATFORM_IDENTITY_ADMIN', 'PLATFORM_ROLE_REMOVE'),
    ('SALES', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('SALES', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('SALES', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('SALES', 'PLATFORM_SESSION_VIEW_SELF'),
    ('SALES', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('SALES', 'LEAD_VIEW'),
    ('SALES', 'LEAD_UPDATE'),
    ('SALES', 'LEAD_ASSIGN'),
    ('ONBOARDING_SPECIALIST', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('ONBOARDING_SPECIALIST', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('ONBOARDING_SPECIALIST', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('ONBOARDING_SPECIALIST', 'PLATFORM_SESSION_VIEW_SELF'),
    ('ONBOARDING_SPECIALIST', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('ONBOARDING_SPECIALIST', 'ORGANIZATION_APPLICATION_VIEW'),
    ('ONBOARDING_SPECIALIST', 'ORGANIZATION_APPLICATION_ASSIGN'),
    ('ONBOARDING_SPECIALIST', 'ORGANIZATION_APPLICATION_REVIEW'),
    ('ONBOARDING_SPECIALIST', 'ORGANIZATION_APPLICATION_VERIFY'),
    ('ONBOARDING_MANAGER', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('ONBOARDING_MANAGER', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('ONBOARDING_MANAGER', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('ONBOARDING_MANAGER', 'PLATFORM_SESSION_VIEW_SELF'),
    ('ONBOARDING_MANAGER', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_APPLICATION_VIEW'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_APPLICATION_ASSIGN'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_APPLICATION_REVIEW'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_APPLICATION_VERIFY'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_APPLICATION_APPROVE'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_APPLICATION_REJECT'),
    ('ONBOARDING_MANAGER', 'ORGANIZATION_VIEW'),
    ('ONBOARDING_MANAGER', 'PROVISIONING_START'),
    ('ONBOARDING_MANAGER', 'PROVISIONING_VIEW'),
    ('ONBOARDING_MANAGER', 'PROVISIONING_RETRY'),
    ('SUPPORT_SPECIALIST', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('SUPPORT_SPECIALIST', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('SUPPORT_SPECIALIST', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('SUPPORT_SPECIALIST', 'PLATFORM_SESSION_VIEW_SELF'),
    ('SUPPORT_SPECIALIST', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('SUPPORT_SPECIALIST', 'ORGANIZATION_VIEW'),
    ('SUPPORT_SPECIALIST', 'SUPPORT_ASSIGNMENT_CREATE'),
    ('SUPPORT_SPECIALIST', 'SUPPORT_ASSIGNMENT_VIEW'),
    ('SUPPORT_SPECIALIST', 'SUPPORT_ASSIGNMENT_REVOKE'),
    ('DATA_MIGRATION_SPECIALIST', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('DATA_MIGRATION_SPECIALIST', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('DATA_MIGRATION_SPECIALIST', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('DATA_MIGRATION_SPECIALIST', 'PLATFORM_SESSION_VIEW_SELF'),
    ('DATA_MIGRATION_SPECIALIST', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('DATA_MIGRATION_SPECIALIST', 'DATA_IMPORT_CREATE'),
    ('DATA_MIGRATION_SPECIALIST', 'DATA_IMPORT_VIEW'),
    ('DATA_MIGRATION_SPECIALIST', 'DATA_IMPORT_VALIDATE'),
    ('DATA_MIGRATION_SPECIALIST', 'DATA_IMPORT_EXECUTE'),
    ('BILLING_ADMIN', 'PLATFORM_PROFILE_VIEW_SELF'),
    ('BILLING_ADMIN', 'PLATFORM_PROFILE_UPDATE_SELF'),
    ('BILLING_ADMIN', 'PLATFORM_PASSWORD_CHANGE_SELF'),
    ('BILLING_ADMIN', 'PLATFORM_SESSION_VIEW_SELF'),
    ('BILLING_ADMIN', 'PLATFORM_SESSION_REVOKE_SELF'),
    ('BILLING_ADMIN', 'PLAN_VIEW'),
    ('BILLING_ADMIN', 'PLAN_ASSIGN'),
    ('BILLING_ADMIN', 'SUBSCRIPTION_VIEW'),
    ('BILLING_ADMIN', 'SUBSCRIPTION_UPDATE')
) AS role_mapping(role, permission_code)
JOIN platform_permissions
    ON platform_permissions.code = role_mapping.permission_code;
