CREATE TABLE platform_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    platform_user_id BIGINT NOT NULL,
    token_family_id UUID NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    family_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by_token_hash VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_platform_refresh_tokens_token_hash
        UNIQUE (token_hash),
    CONSTRAINT fk_platform_refresh_tokens_user
        FOREIGN KEY (platform_user_id)
            REFERENCES platform_users(id)
            ON DELETE CASCADE
);

CREATE INDEX idx_platform_refresh_tokens_user_active
    ON platform_refresh_tokens(platform_user_id)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_platform_refresh_tokens_family_active
    ON platform_refresh_tokens(token_family_id)
    WHERE revoked_at IS NULL;

ALTER TABLE platform_refresh_tokens
    ALTER COLUMN version DROP DEFAULT;

CREATE TABLE platform_security_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_platform_user_id BIGINT,
    action VARCHAR(80) NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT,
    request_id VARCHAR(120),
    ip_address VARCHAR(80),
    details VARCHAR(1000),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_platform_security_audit_actor
        FOREIGN KEY (actor_platform_user_id)
            REFERENCES platform_users(id)
            ON DELETE SET NULL
);

CREATE INDEX idx_platform_security_audit_events_occurred
    ON platform_security_audit_events (occurred_at DESC);

CREATE INDEX idx_platform_security_audit_events_actor_action
    ON platform_security_audit_events (
        actor_platform_user_id,
        action,
        occurred_at DESC
    );

CREATE INDEX idx_platform_security_audit_events_target
    ON platform_security_audit_events (
        target_type,
        target_id,
        occurred_at DESC
    );
