CREATE TABLE platform_user_password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    platform_user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_platform_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_platform_password_reset_user FOREIGN KEY (platform_user_id)
        REFERENCES platform_users(id) ON DELETE CASCADE
);

CREATE INDEX idx_platform_password_reset_active_user
    ON platform_user_password_reset_tokens (platform_user_id)
    WHERE used_at IS NULL AND revoked_at IS NULL;
