ALTER TABLE users
    ADD CONSTRAINT uk_users_id_organization
        UNIQUE (id, organization_id);

CREATE TABLE student_guardian_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL,
    student_user_id BIGINT NOT NULL,
    guardian_user_id BIGINT NOT NULL,

    relationship_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    primary_guardian BOOLEAN NOT NULL DEFAULT FALSE,

    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP WITH TIME ZONE,

    created_by_user_id BIGINT NOT NULL,
    ended_by_user_id BIGINT,
    end_reason VARCHAR(500),

    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_student_guardian_relationships_positive_ids
        CHECK (
            id > 0
            AND organization_id > 0
            AND student_user_id > 0
            AND guardian_user_id > 0
            AND created_by_user_id > 0
            AND (ended_by_user_id IS NULL OR ended_by_user_id > 0)
        ),

    CONSTRAINT chk_student_guardian_relationships_distinct_users
        CHECK (student_user_id <> guardian_user_id),

    CONSTRAINT chk_student_guardian_relationships_type
        CHECK (
            relationship_type IN (
                'MOTHER',
                'FATHER',
                'GUARDIAN',
                'OTHER'
            )
        ),

    CONSTRAINT chk_student_guardian_relationships_status
        CHECK (status IN ('ACTIVE', 'ENDED')),

    CONSTRAINT chk_student_guardian_relationships_lifecycle
        CHECK (
            (
                status = 'ACTIVE'
                AND ended_at IS NULL
                AND ended_by_user_id IS NULL
            )
            OR (
                status = 'ENDED'
                AND ended_at IS NOT NULL
                AND ended_by_user_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_student_guardian_relationships_end_reason_not_blank
        CHECK (
            end_reason IS NULL
            OR length(trim(end_reason)) > 0
        ),

    CONSTRAINT chk_student_guardian_relationships_version
        CHECK (version >= 0),

    CONSTRAINT fk_student_guardian_relationships_student_user
        FOREIGN KEY (student_user_id, organization_id)
            REFERENCES users (id, organization_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_guardian_relationships_guardian_user
        FOREIGN KEY (guardian_user_id, organization_id)
            REFERENCES users (id, organization_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_guardian_relationships_created_by_user
        FOREIGN KEY (created_by_user_id, organization_id)
            REFERENCES users (id, organization_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_student_guardian_relationships_ended_by_user
        FOREIGN KEY (ended_by_user_id, organization_id)
            REFERENCES users (id, organization_id)
            ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_student_guardian_relationships_active_pair
    ON student_guardian_relationships (
        organization_id,
        student_user_id,
        guardian_user_id
    )
    WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX uk_student_guardian_relationships_active_primary
    ON student_guardian_relationships (
        organization_id,
        student_user_id
    )
    WHERE status = 'ACTIVE'
      AND primary_guardian = TRUE;

CREATE INDEX idx_student_guardian_relationships_student_history
    ON student_guardian_relationships (
        organization_id,
        student_user_id,
        started_at DESC,
        id DESC
    );

CREATE INDEX idx_student_guardian_relationships_guardian_active_students
    ON student_guardian_relationships (
        organization_id,
        guardian_user_id,
        status,
        student_user_id
    );

INSERT INTO permissions (
    code,
    description,
    owning_service,
    sensitive,
    active
)
VALUES
    (
        'STUDENT_GUARDIAN_RELATIONSHIP_VIEW',
        'View student-guardian relationships',
        'identity-service',
        FALSE,
        TRUE
    ),
    (
        'STUDENT_GUARDIAN_RELATIONSHIP_MANAGE',
        'Create, update primary contact, and end student-guardian relationships',
        'identity-service',
        TRUE,
        TRUE
    )
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permissions (
    role,
    permission_id
)
SELECT
    roles.role,
    permissions.id
FROM (
         VALUES
             ('ADMIN'),
             ('PRINCIPAL'),
             ('VICE_PRINCIPAL'),
             ('ADMISSIONS_OFFICER')
     ) AS roles(role)
         CROSS JOIN permissions
WHERE permissions.code IN (
    'STUDENT_GUARDIAN_RELATIONSHIP_VIEW',
    'STUDENT_GUARDIAN_RELATIONSHIP_MANAGE'
)
ON CONFLICT (role, permission_id) DO NOTHING;
