CREATE TABLE school_phone_normalization_reviews
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table VARCHAR(100) NOT NULL,
    source_column VARCHAR(100) NOT NULL,
    source_id BIGINT NOT NULL,
    current_value VARCHAR(20) NOT NULL,
    proposed_e164_value VARCHAR(20),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by VARCHAR(150),
    notes VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_school_phone_normalization_review_status
        CHECK (status IN (
            'PENDING_REVIEW',
            'APPROVED',
            'REJECTED',
            'APPLIED'
        ))
);

CREATE INDEX idx_school_phone_normalization_reviews_source
    ON school_phone_normalization_reviews(
        source_table,
        source_column,
        source_id
    );
